import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/layout/Header";
import Footer from "./Components/layout/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <main className=" mx-auto  p-4">
          <Header />
          {children}
          <Footer />
        </main>
        </body>
    </html>
  );
}
